version: 2.1

orbs:
  architect: giantswarm/architect@4.0.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: k8s-kvm-health
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: "quay.io/giantswarm/k8s-kvm-health"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/